### ISSUE TITLE
UI: Clean Up UI

### ISSUE THREAD

**Issue by BlenderDefender** [PidgeonTools/SuperProjectManager#26]
```[tasklist]
### Tasks
- [x] Clean up the UI of the Project Starter Panel for better usability.
- [x] Note: Maybe remove the subpanel for "Save Blender File / Options", because subpanels appear to always be located at the bottom of the layout.
- [ ] https://github.com/PidgeonTools/SuperProjectManager/issues/25
- [ ] https://github.com/PidgeonTools/SuperProjectManager/issues/27
- [ ] https://github.com/PidgeonTools/SuperProjectManager/issues/32
- [ ] https://github.com/PidgeonTools/SuperProjectManager/issues/31
- [ ] https://github.com/PidgeonTools/SuperProjectManager/issues/34
```
