### ISSUE TITLE
Feature: Add file browser panel that displays relevant project files and folders

### ISSUE THREAD

**Issue by BlenderDefender** [PidgeonTools/SuperProjectManager#36]
Idea from Arri on Discord: I liked the idea of you addon, and would like to know if it was possible to potentially commission something similarish...   I come from XSI and Maya, and a nice thing they have is set project.  This enables you file browser to be set to the specific project you are working on, and in the file View (open scenes etc)  all the relevant paths for the project are there.  Something like this mock up.

![Image](https://user-images.githubusercontent.com/61777131/250095390-460d58ca-7441-4894-bd39-848eed85c4cb.png)

```[tasklist]
### Tasks
- [x] Step One: Find a way to draw a panel like the one that's shown in the mockup
- [x] Step Two: Find a way to add custom paths to that panel
- [x] Step Three: Add a dropdown (enum property) above the panel that allows to switch between projects. The enum prop should maybe contain values specified in the global settings file
- [x] Step Four: Add a way to customize the Folders that are shown (maybe "Hide" in the context menu) for a project -> Stored in .blender_pm metadata file
```
